# Feature selection

F = $\{x_ox_1x_2x_4$\}

#More information doesn't always means better classification ->
#. Irrevelant data
#Reduce Overfitting improve accuracy reduce training time.

## Ways to select features

1. Univariate Selection
2. Recursive Feature Elimation
3. Principle Component Analysis
4. Feature Importance Selection



In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, Math


c:\users\abugh\appdata\local\programs\python\python38\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\users\abugh\appdata\local\programs\python\python38\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
c:\users\abugh\appdata\local\programs\python\python38\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:\n%s" %


In [2]:
hnames = ['preg', 'plas',  'press', 'skin', 'ins', 'mass', 'fun', 'age', 'out']
df = pd.read_csv("indians_diabetes.csv", names=hnames)

X = df.iloc[:,:-1].values
Y = df.iloc[:,-1].values
df.head()

preg  plas  press  skin  ins  mass    fun  age  out
0     6   148     72    35    0  33.6  0.627   50    1
1     1    85     66    29    0  26.6  0.351   31    0
2     8   183     64     0    0  23.3  0.672   32    1
3     1    89     66    23   94  28.1  0.167   21    0
4     0   137     40    35  168  43.1  2.288   33    1

In [3]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X,Y)

#Greater score has greater accuracy/ select by columns for training.
fit.scores_

array([ 111.51969064, 1411.88704064,   17.60537322,   53.10803984,
       2175.56527292,  127.66934333,    5.39268155,  181.30368904])

In [4]:
x = df.iloc[:,[1,4,5,7]]
y = df['out']

In [5]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=9, test_size = 0.3)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(x_train, y_train)

y_predict = model.predict(x_test)

from sklearn.metrics import accuracy_score

print(f"Accuracy: {accuracy_score(y_test, y_predict)*100}%")

Accuracy: 73.59307359307358%


# Recursive Feature Elimination

In [6]:
import warnings
warnings.filterwarnings(action="ignore")

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

from sklearn.feature_selection import RFE
rfe = RFE(model, 4)
fit = rfe.fit(X,Y)

result_x = fit.transform(X)

print(f"Num Feature: {fit.n_features_}")
print(f"Num Feature: {fit.ranking_}")

Num Feature: 4
Num Feature: [1 1 3 4 5 1 1 2]


In [19]:
print(result_x)

[[  6.    148.     33.6     0.627]
 [  1.     85.     26.6     0.351]
 [  8.    183.     23.3     0.672]
 ...
 [  5.    121.     26.2     0.245]
 [  1.    126.     30.1     0.349]
 [  1.     93.     30.4     0.315]]


In [28]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(result_x, y, random_state=3, test_size = 0.3)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(x_train, y_train)

y_predict = model.predict(x_test)

from sklearn.metrics import accuracy_score

print(f"Accuracy: {accuracy_score(y_test, y_predict)*100}%")

Accuracy: 72.72727272727273%


# Principal Component Analysis

It tries to view data from different prospective\
and analyse the best one

In [22]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
fit = pca.fit(X, Y)

result_x = pca.transform(X)

print(fit.components_)
print(result_x)

[[-2.02176587e-03  9.78115765e-02  1.60930503e-02  6.07566861e-02
   9.93110844e-01  1.40108085e-02  5.37167919e-04 -3.56474430e-03]
 [-2.26488861e-02 -9.72210040e-01 -1.41909330e-01  5.78614699e-02
   9.46266913e-02 -4.69729766e-02 -8.16804621e-04 -1.40168181e-01]
 [-2.24649003e-02  1.43428710e-01 -9.22467192e-01 -3.07013055e-01
   2.09773019e-02 -1.32444542e-01 -6.39983017e-04 -1.25454310e-01]]
[[-75.71465491 -35.95078264  -7.26078895]
 [-82.3582676   28.90821322  -5.49667139]
 [-74.63064344 -67.90649647  19.46180812]
 ...
 [ 32.11319827   3.3766648   -1.58786446]
 [-80.21449431 -14.18601977  12.3512639 ]
 [-81.30814972  21.62149606  -8.15276833]]


In [ ]:
#TODO -> Create model and check the accuracy

# Feature Importance Selection
used in Decision Tree and Random Forest

In [26]:
from sklearn.ensemble import ExtraTreesClassifier

classifier = ExtraTreesClassifier()
classifier.fit(X,Y)

f"Score: {classifier.feature_importances_}"

'Score: [0.10987292 0.23944471 0.09864956 0.07678149 0.07732617 0.14381639\n 0.11657113 0.13753762]'

# Coveriance

In [32]:
display(Math("\\text{Cov(x, y)} = \\frac{\\sum{(x-\\bar{x})(y-y')}}{n-1}"))

<IPython.core.display.Math object>