In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



In [12]:
hnames = ['preg', 'plas',  'press', 'skin', 'ins', 'mass', 'fun', 'age', 'out']
df = pd.read_csv("indians_diabetes.csv", names=hnames)

X = df.iloc[:,:-1].values
Y = df.iloc[:,-1].values

df.head()

preg  plas  press  skin  ins  mass    fun  age  out
0     6   148     72    35    0  33.6  0.627   50    1
1     1    85     66    29    0  26.6  0.351   31    0
2     8   183     64     0    0  23.3  0.672   32    1
3     1    89     66    23   94  28.1  0.167   21    0
4     0   137     40    35  168  43.1  2.288   33    1

In [10]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X,Y)

#Greater score has greater accuracy/ select by columns for training.
fit.scores_

array([ 111.51969064, 1411.88704064,   17.60537322,   53.10803984,
       2175.56527292,  127.66934333,    5.39268155,  181.30368904])

In [13]:
x = df.iloc[:,[1,4,5,7]]
x

plas  ins  mass  age
0     148    0  33.6   50
1      85    0  26.6   31
2     183    0  23.3   32
3      89   94  28.1   21
4     137  168  43.1   33
..    ...  ...   ...  ...
763   101  180  32.9   63
764   122    0  36.8   27
765   121  112  26.2   30
766   126    0  30.1   47
767    93    0  30.4   23

[768 rows x 4 columns]

In [ ]:
#TODO -> Create model and check the accuracy

# Recursive Feature Elimination

In [18]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

from sklearn.feature_selection import RFE
rfe = RFE(model, 4)
fit = rfe.fit(X,Y)

result_x = fit.transform(X)

print(f"Num Feature: {fit.n_features_}")
print(f"Num Feature: {fit.ranking_}")

Num Feature: 4
Num Feature: [1 1 3 4 5 1 1 2]


c:\users\abugh\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:68: FutureWarning: Pass n_features_to_select=4 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "
c:\users\abugh\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [19]:
print(result_x)

[[  6.    148.     33.6     0.627]
 [  1.     85.     26.6     0.351]
 [  8.    183.     23.3     0.672]
 ...
 [  5.    121.     26.2     0.245]
 [  1.    126.     30.1     0.349]
 [  1.     93.     30.4     0.315]]


In [ ]:
#TODO -> Create model and check the accuracy

# Principal Component Analysis

It tries to view data from different prospective\
and analyse the best one

In [22]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
fit = pca.fit(X, Y)

result_x = pca.transform(X)

print(fit.components_)
print(result_x)

[[-2.02176587e-03  9.78115765e-02  1.60930503e-02  6.07566861e-02
   9.93110844e-01  1.40108085e-02  5.37167919e-04 -3.56474430e-03]
 [-2.26488861e-02 -9.72210040e-01 -1.41909330e-01  5.78614699e-02
   9.46266913e-02 -4.69729766e-02 -8.16804621e-04 -1.40168181e-01]
 [-2.24649003e-02  1.43428710e-01 -9.22467192e-01 -3.07013055e-01
   2.09773019e-02 -1.32444542e-01 -6.39983017e-04 -1.25454310e-01]]
[[-75.71465491 -35.95078264  -7.26078895]
 [-82.3582676   28.90821322  -5.49667139]
 [-74.63064344 -67.90649647  19.46180812]
 ...
 [ 32.11319827   3.3766648   -1.58786446]
 [-80.21449431 -14.18601977  12.3512639 ]
 [-81.30814972  21.62149606  -8.15276833]]


In [ ]:
#TODO -> Create model and check the accuracy

# Feature Importance Selection
used in Decision Tree and Random Forest

In [26]:
from sklearn.ensemble import ExtraTreesClassifier

classifier = ExtraTreesClassifier()
classifier.fit(X,Y)

f"Score: {classifier.feature_importances_}"

'Score: [0.10987292 0.23944471 0.09864956 0.07678149 0.07732617 0.14381639\n 0.11657113 0.13753762]'